services:
  #服务根节点
  redis:
    image: redis:7.4.1
    container_name: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  redis-data:
    driver: local
