definitions:
  api.versionResponse:
    properties:
      buildTime:
        type: string
      commitHash:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/system/version:
    get:
      description: Returns the application's current version, build time, and commit
        hash
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.versionResponse'
      summary: Get version information
      tags:
      - system
swagger: "2.0"
